### ISSUE TITLE
Package dependency issue

### ISSUE THREAD

**Issue by chinghwayu** [JKISoftware/JKI-VI-Tester-JUnit-XML-Test-Results#1]
Upon installation, VIPM complains of a missing "jki_rsc_palette" package. However, upon installation, no code is broken.

Should this point to "jki_rsc_toolkits_palette" instead?

![junit_missing_package](https://cloud.githubusercontent.com/assets/11654708/25590214/67045a32-2e64-11e7-8f55-5050438d7ac3.png)

**Comment by jimkring** [comment]
Thanks @chinghwayu! Fixed and released in 2.0.1.
https://github.com/JKISoftware/JKI-VI-Tester-JUnit-XML-Test-Results/releases/tag/2.0.1

Should be available for download in VIPM, shortly.
